spring:
  profiles:  # database config include
    include: database
  jpa:
    hibernate:
      ddl-auto: create
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /static/**


# logger 설정
logging:
  level:
    root: info