spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dori_dev
  config:
    import: optional:classpath:secrets.yml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: health,info,beans,conditions,loggers,note
  info:
    env:
      enabled: true

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://localhost:3306/dori_test